stages:
  - test

test_app:
  image: python:latest
  stage: test
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv .env
    - python -m venv .env
    - source .env/bin/activate

  script:
    - pip install -r requirements.txt
    # - flask run
    # - python test_server/test_login.py
    # - python test_server/test_survey.py
    - python test_server/test_tes_server.py
